---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kerni.
--- DateTime: 15/09/2021 00:53
---
Player = {}

Player.ID = nil
Player.Ped = nil
Player.Skin = false

Player.Pos = vector3(0,0,0)
Player.Heading = 0.0
Player.Health = 0
Player.Armor = 0
Player.IsShooting = false


Player.Noclip = false
Player.IsInvisible = false
Player.IsInvincible = false
Player.InMenu = false

Citizen.CreateThread(function()
    DecorRegister("myId", 3)
    TriggerServerCallback("kernioz:getMyId", function(cb)
        local pPed = GetPlayerPed(-1)
        DecorSetInt(pPed, "myId", cb)
    end)
end)

Citizen.CreateThread(function()
    Player.ID = PlayerId()
    while true do
        Player.Ped = GetPlayerPed(-1)
        Player.Pos = GetEntityCoords(Player.Ped)
        Player.Heading = GetEntityHeading(Player.Ped)
        Player.Health = GetEntityHealth(Player.Ped)
        Player.Armor = GetPedArmour(Player.Ped)
        Player.IsShooting = IsPedShooting(Player.Ped)
        Citizen.Wait(150)
    end
end)

Citizen.CreateThread(function()
    while true do
        Wait(1*1000)
        Player.IsInVehicle = IsPedInAnyVehicle(Player.Ped, false)
        Player.Vehicle = GetVehiclePedIsIn(Player.Ped, false)
        Player.IsDriver = GetPedInVehicleSeat(GetVehiclePedIsIn(Player.Ped, false), -1) == Player.Ped
        Player.Zone = GetNameOfZone(Player.Pos)
        Player.IsArmed = IsPedArmed(Player.Ped, 5)
        Player.IsCuffed = IsPedCuffed(Player.Ped)
        Player.ZoneGlobal = kUtils.GetZonesFromPlayer(Player)

        Player.Health = GetEntityHealth(Player.Ped)
        Player.Armor = GetPedArmour(Player.Ped)
    end
end)
